apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
spec:
  rules:
  - http:
      paths:
      - path: /web/*
        backend:
          serviceName: webapp-service
          servicePort: 5000
      - path: /*
        backend:
          serviceName: statsapp-service
          servicePort: 8050
