apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: statsapp--ingress
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: statsapp-service
          servicePort: 8050
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webapp-ingress
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: webapp-service
          servicePort: 5000
