apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: statsapp-service
    servicePort: 8050
  rules:
  - http:
      paths:
      - path: /web/*
        backend:
          serviceName: webapp-service
          servicePort: 5000
      
      
      
