apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: webapp
          servicePort: 5000
      - path: /statistic
        backend:
          serviceName: statsapp
          servicePort: 8050
