apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    component: mongodb
spec:
  selector:
    component: mongodb
  ports:
  - name: mongodb
    port: 27017
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb
  labels:
    component: mongodb
spec:
  selector:
    matchLabels:
      component: mongodb
  template:
    metadata:
      name: mongodb
      labels:
        component: mongodb
    spec:
      containers:
      - name: mongodb
        image: docker.io/bitnami/mongodb:4.0.6
        ports:
        - name: mongodb
          protocol: TCP
          containerPort: 27017
