apiVersion: v1
kind: Service
metadata:
  name: statsapp-service
spec:
  type: NodePort
  selector:
    component: statsapp
  ports:
  - protocol: TCP
    port: 8050
    targetPort: 8050
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: statsapp
  labels:
    component: statsapp
spec:
  selector:
    matchLabels:
      component: statsapp
  template:
    metadata:
      name: statsapp
      labels:
        component: statsapp
    spec:
      containers:
      - name: statsapp
        image: gcr.io/hackathon-19/stats-hack2019:0.0.5
        env:
        - name: MONGO_URI
          value: mongodb://mongodb:27017
        ports:
        - name: http
          protocol: TCP
          containerPort: 8050
